language: elixir

matrix:
  include:
    - elixir: '1.8'
      otp_release: '20.3'
    - elixir: '1.8'
      otp_release: '21.1'
    - elixir: '1.8'
      otp_release: '22.0'
    - elixir: '1.9'
      otp_release: '20.3'
    - elixir: '1.9'
      otp_release: '21.1'
    - elixir: '1.9'
      otp_release: '22.0'
    - elixir: '1.10'
      otp_release: '22.3'

script:
  - "mix"
